# Generated by Django 4.1.5 on 2023-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prodapp',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('TS', 'T-SHIRTS'), ('HO', 'HOODIES'), ('BO', 'BOOKS'), ('JO', 'JOURNAL'), ('PO', 'PROFIT DIARY'), ('GA', 'GAMES')], max_length=2),
        ),
    ]
