# Generated by Django 4.1.5 on 2023-01-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
